name: trading_instruments
description: "A flutter app to list trading instruments and real time price"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  dio: 5.2.0+1
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3
  web_socket_channel: ^3.0.1
  api_client:
    path: packages/core/api_client
  utils:
    path: packages/core/utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^0.2.0
  bloc_test: ^8.1.0

flutter:
  uses-material-design: true




